### PR TITLE
Development/user bookings

### PR DESCRIPTION
**Pull request by therealedsheenan**
- user bookings pages
- separate accounts layout

### CODE REVIEW

**Comment by therealedsheenan** [comment]
I'm not sure with the name of the actual `path` of the routes for `bookings` page.
Since we already have `users/:slug`. So I just used `user/bookings` instead.

**Comment by SachaG** [comment]
Sorry, I guess my instructions weren't very clear, this wasn't really what I had in mind… Anyway I'll fix it and you can see for yourself. 

One thing though, please do not include spacing/semi-colon/etc. fixes in the same PRs, it makes it harder to know exactly what has been changed.

**Comment by therealedsheenan** [comment]
Sorry about that. Will ask you thoroughly next time.

About the spacing, semi-colons etc.., I think those are automated in my IDE.
I'll try to disable it next time.

**Comment by SachaG** [comment]
Here's my improvements:

https://github.com/SachaG/Zensroom/commit/720e96f90c4c20b0283076d326cb190d830bea57

`AccountLayout` doesn't change the current header, it only adds an additional nav to navigate between `/account` and `/account/bookings`. 

And for the IDE, it's not a big deal if they're changed by the IDE, just include them in a different PR :)

**Pull request merged**
